
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 25 21:26:11 EEST 2018
//----------------------------------------------------

package org.hua;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 44;
  public static final int LBRACKET = 22;
  public static final int GREATER_OR_EQUAL = 18;
  public static final int EQUALS = 20;
  public static final int UMINUS = 13;
  public static final int LPAREN = 4;
  public static final int GREATER = 16;
  public static final int CONTINUE = 29;
  public static final int INT = 38;
  public static final int LESS = 17;
  public static final int MINUS = 12;
  public static final int WRITE = 3;
  public static final int STATIC = 36;
  public static final int RPAREN = 5;
  public static final int NOT = 24;
  public static final int SEMICOLON = 6;
  public static final int AND = 14;
  public static final int LESS_OR_EQUAL = 19;
  public static final int OR = 15;
  public static final int COMMA = 27;
  public static final int CLASS = 33;
  public static final int PLUS = 11;
  public static final int IF = 31;
  public static final int THIS = 35;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int RBRACKET = 23;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int NULL = 37;
  public static final int MOD = 10;
  public static final int BREAK = 28;
  public static final int VOID = 41;
  public static final int EQ = 7;
  public static final int TIMES = 8;
  public static final int ELSE = 32;
  public static final int WHILE = 25;
  public static final int NOT_EQUALS = 21;
  public static final int FLOAT = 39;
  public static final int STRING = 40;
  public static final int FLOAT_LITERAL = 43;
  public static final int DIVISION = 9;
  public static final int INTEGER_LITERAL = 42;
  public static final int IDENTIFIER = 2;
}

